---
- hosts: blahblahblah
  sudo: yes
  tasks:
  - user: name=bconnelly comment="My User" group=wheel
  - name: Placing key
    authorized_key: user=myuser key="{{ lookup('file', './files/benjamin.t.connelly@gmail.pub') }}"
