---
- name: Symlink my dotfiles
  file: src=~/.dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .vimrc
    - .bashrc
    - .bash_profile
    - .profile

- name: Clone Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: Install/update VIM plugins
  command: echo | echo | vim +PluginInstall +qall &>/dev/null
