---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Tap fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - awscli
    - cask
    - ccat
    - coreutils
    - curl
    - fasd
    - findutils
    - git
    - hub
    - jq
    - mas
    - mosh
    - nmap
    - node
    - openssl
    - p7zip
    - pandoc
    - python
    - python3
    - readline
    - rename
    - screenfetch
    - ssh-copy-id
    - tldr
    - tree
    - vim
    - watch
    - wget
    - youtube-dl
    - htop
    - tmux

- name: Install apps with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - xquartz
    - aerial
    - alfred
    - appcleaner
    - atom
    - au-lab
    - google-chrome
    - daisydisk
    - hipchat
    - mattr-slate
    - mactex
    - postman
    - qlcolorcode
    - qlmarkdown
    - qlprettypatch
    - qlstephen
    - quicklook-csv
    - quicklook-json
    - skype
    - slack
    - soundflower
    - tunnelblick
    - vagrant
    - vagrant-manager
    - virtualbox
    - vlc
    - whatsapp
    - xld

- name: Cleanup Brew packages
  command: brew cleanup
