---
- name: Install PIP packages
  pip: name={{ item }}
  with_items:
    - fabric
    - flake8
    - howdoi
    - ipython
    - mycli
    - pylint
    - pythonpy
    - speedtest-cli
    - termrule
    - virtualenv
    - virtualenvwrapper
